### ISSUE TITLE
Docker image not runable

### ISSUE THREAD

**Issue by SchulteMarkus** [pact-foundation/pact-ruby-cli#2]
I cannot run the docker image pactfoundation/pact-cli

```bash
$ docker run --rm -e PACT_BROKER_BASE_URL pactfoundation/pact-cli publish \
    build/pacts --consumer-app-version <some-git-sha1>$(date +%s)

bundler: failed to load command: bin/pact (bin/pact)
Errno::ENOENT: No such file or directory @ rb_sysopen - app/build/pacts
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/pact_file.rb:32:in `read'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/pact_file.rb:32:in `read'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/pact_file.rb:28:in `pact_hash'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/pact_file.rb:16:in `pact_name'
  /usr/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/file_list.rb:81:in `each'
  /usr/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/file_list.rb:81:in `group_by'
  /usr/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/file_list.rb:81:in `group_by'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/publish_pacts.rb:41:in `publish_pacts'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/publish_pacts.rb:27:in `call'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/publish_pacts.rb:13:in `call'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/cli/broker.rb:196:in `publish_pacts'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/cli/broker.rb:57:in `publish'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.19.0/lib/pact_broker/client/cli/custom_thor.rb:15:in `start'
  /pact/lib/pact/cli.rb:54:in `publish'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  bin/pact:9:in `<top (required)>'
```

**Comment by SchulteMarkus** [comment]
Sorry, my mistake. 
The directory _build/pacts_ did not exist
