### ISSUE TITLE
NoMethodError - `request_uri`

### ISSUE THREAD

**Issue by robotoer** [pact-foundation/pact-ruby-cli#42]
I have been getting the following error when trying to run the `pact-broker publish ...` command:

```
[2022-01-28T17:26:48.933Z] $ pact-broker publish pacts/ --consumer-app-version="${npm_package_version}" --broker-base-url=$PACT_BROKER_URL --broker-username=$PACT_BROKER_USERNAME --broker-password=$PACT_BROKER_PASSWORD --tag test-pact-publish
[2022-01-28T17:26:50.330Z] /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/hal/http_client.rb:49:in `create_request': undefined method `request_uri' for #<URI::Generic:0x00560d17401008> (NoMethodError)
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/hal/http_client.rb:25:in `get'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/hal/link.rb:41:in `get'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/hal/link.rb:45:in `get!'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/hal_client_methods.rb:20:in `index_resource'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/-pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/publish_pacts.rb:31:in `call'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/publish_pacts.rb:14:in `call'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/cli/broker.rb:157:in `publish_pacts'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/cli/broker.rb:42:in `publish'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.58.0/lib/pact_broker/client/cli/custom_thor.rb:15:in `start'
[2022-01-28T17:26:50.330Z] 	from /jenkins_work/jaas/workspace/pact-publish/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/lib/app/pact-broker.rb:34:in `<main>'
```

Any ideas on what might be causing this?

**Comment by robotoer** [comment]
Oops, posted this issue to the wrong project!
